# _config.yml
title: "Sustainable Waste Resource Recovery Lab"
description: "UT Austin | Fariborz Maseeh Dept. of Civil, Architectural & Environmental Engineering"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache

include:
  - assets/css/custom.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
